      # General
      set -g aggressive-resize on
      set -g base-index 1
      set -g bell-action none
      set -g default-terminal "screen-256color"
      #set -ga terminal-overrides ",xterm-256color:RGB"
      set -g mouse on
      #set -g prefix C-a
      set -sg escape-time 10
      setw -g mode-keys vi
      #setw -g xterm-keys on
      set -g status-bg black
      set -g status-fg white
      # set -g status-bg green
      # set -g status-fg colour232

      # Status Bar
      set -g status-interval 1
      set -g status-position top
      #set -g status-right '#(date +"%b %_d %H:%M")   #(whoami)@#(hostname -s)   #(free -m | awk "NR==2{printf \"DISK %s/%s (%.2f%%)\", $3,$2,$3*100/$2 }")   #(df -h | awk "$NF==\"/\"{printf \"RAM %d/%d (%s)\n\", $3,$2,$5}") #(top -bn1 | grep load | awk "{printf \"CPU %.2f\n\", $(NF-2)}")'
      #echo "CPU `LC_ALL=C top -bn1 | grep "Cpu(s)" | sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | awk '{print 100 - $1}'`% RAM `free -m | awk '/Mem:/ { printf("%3.1f%%", $3/$2*100) }'` HDD `df -h / | awk '/\// {print $(NF-1)}'`"
      #set -g status-right 
      set -g status-right "%m-%d-%y %H:%M #(tmux-mem-cpu-load -a 0 -q)"
      set -g status-right-length 60
      set -g status-left " "
      set -g status-left-length 0

      set-window-option -g window-status-current-format "#[bold]#W#[nobold]"
      set-window-option -g window-status-format "#W"

      # Colors for pane borders(default)
      setw -g pane-border-style fg=black,bg=colour232
      setw -g pane-active-border-style fg=white,bg=colour232

      # Active pane normal, other shaded out
      #setw -g window-style fg=colour240,bg=colour235
      #setw -g window-active-style fg=white,bg=black

      # Key Bindings
      bind r source-file /etc/tmux.conf
      #bind ! split-window -h -c "#{pane_current_path}"
      #bind - split-window -v -c "#{pane_current_path}"
      #bind b break-pane
      #bind k confirm kill-window
      #bind q confirm kill-session
      #bind t select-layout tiled
      #bind x kill-pane

      #bind -n S-Left previous-window
      #bind -n S-Right next-window

      #bind -n M-S-Left resize-pane -L 5
      #bind -n M-S-Right resize-pane -R 5
      #bind -n M-S-Down resize-pane -D 5
      #bind -n M-S-Up resize-pane -U 5

      # vim-like Copy & Paste
      bind Escape copy-mode
      bind p paste-buffer
      bind -T copy-mode-vi v send -X begin-selection
      bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel
      bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-selection-and-cancel
      bind -T copy-mode-vi Enter send-keys -X copy-selection-and-cancel

      # macOS Copy & Paste
      if-shell 'test "$(uname)" = "Darwin"' \
        'bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"; \
         bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"; \
         bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "pbcopy"'
